var clearTimeout;
var encodeURIComponent;
var decodeURIComponent;
Window.prototype.document;
Window.prototype.Slider;
Window.prototype.requestAnimationFrame;
Window.prototype.webkitRequestAnimationFrame;
Window.prototype.mozRequestAnimationFrame;
Window.prototype.msRequestAnimationFrame;
Window.prototype.crypto.getRandomValues;
Window.prototype.setTimeout;
Object.defaultValue;
Object.textContent;
Object.onChange;
Object.useState;
Object.download;
Object.memo;
Object.href;
Object.Fragment;
Object.index;
Object.exec;
Object.ref;
Object.ref.hasOwnProperty;
Object.ref.current;
Object.useRef;
Object.value;
Object.findDOMNode;
Object.Component;
Object.Component.call;
Object.Children;
Object.Children.toArray;
Object.useEffect;
Object.click;
Object.removeAllRanges;
Object.render;
Object.addRange;
Object.out;
Object.out.println;
Object.createElement;
Object.createElement.apply;
Object.unmountComponentAtNode;
Object.error;
Object.error.println;
Object.selectNode;
Object.hasOwnProperty;
var clearInterval;
Navigator.prototype.clipboard;
Navigator.prototype.clipboard.writeText;
HTMLDocument.prototype.getElementById;
HTMLDocument.prototype.activeElement;
HTMLDocument.prototype.querySelector;
HTMLDocument.prototype.createElement;
HTMLDocument.prototype.getSelection;
HTMLDocument.prototype.createRange;
HTMLDocument.prototype.execCommand;
var process;
process.hrtime;
JSON.parse;
JSON.stringify;
var require;
require.resolve;
var setInterval;
var setTimeout;
var jwplayer;
HTMLBodyElement.prototype.innerHTML;
HTMLBodyElement.prototype.appendChild;
HTMLBodyElement.prototype.removeChild;
var React;
React.Component;
React.Component.prototype.forceUpdate;
React.Component.prototype.cljsIsDirty;
React.Component.prototype.constructor$;
React.Component.prototype.props;
React.Component.prototype.props.argv;
React.Component.prototype.props.children;
Date.prototype.cljs_time$coerce$ICoerce$;
Date.prototype.cljs_time$coerce$ICoerce$to_date_time$arity$1;
Java.type;
var ReactTestUtils;
ReactTestUtils.Simulate;
ReactTestUtils.Simulate.drag;
ReactTestUtils.Simulate.dragEnter;
ReactTestUtils.Simulate.change;
ReactTestUtils.Simulate.keyUp;
ReactTestUtils.Simulate.dragStart;
ReactTestUtils.Simulate.keyPress;
ReactTestUtils.Simulate.mouseLeave;
ReactTestUtils.Simulate.mouseMove;
ReactTestUtils.Simulate.mouseDown;
ReactTestUtils.Simulate.dragOver;
ReactTestUtils.Simulate.dragLeave;
ReactTestUtils.Simulate.drop;
ReactTestUtils.Simulate.mouseEnter;
ReactTestUtils.Simulate.click;
ReactTestUtils.Simulate.blur;
ReactTestUtils.Simulate.dragEnd;
ReactTestUtils.Simulate.touchstart;
ReactTestUtils.Simulate.touchend;
ReactTestUtils.Simulate.keyDown;
ReactTestUtils.Simulate.mouseUp;
ReactTestUtils.Simulate.focus;
var clj_nil;
